language: node_js
node_js:
  # latest LTS as of 10/01/2020
  - "14.17.0"
# Need a C++ compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  chrome: stable
env:
  - CXX=g++-4.8
cache:
  directories:
    - node_modules
script:
  - npm run light-house
  - npm run travis
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false
